import { invoke } from '../lib/tauri';
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import type {
  AppSettings,
  ApprovalEntry,
  ApprovalLevel,
  ApprovalScope,
  BgAgentSummary,
  PersistentApprovalEntry,
  SessionId,
  ToolCallId,
} from '@forge/ipc';

export const SESSION_EVENT = 'session:event';

/** Mirror of `forge_ipc::HelloAck`. */
export interface HelloAck {
  session_id: string;
  workspace: string;
  started_at: string;
  event_seq: number;
  schema_version: number;
}

/** Payload emitted by the shell's bridge reader task. */
export interface SessionEventPayload {
  session_id: SessionId;
  seq: number;
  event: unknown;
}

/**
 * F-052 (H11 / T7): `session_hello` takes no socket-path override. The Rust
 * command has no `socketPath` parameter — any such field in the invoke
 * payload is silently dropped by serde before the command runs, and the
 * shell resolves the UDS exclusively via `default_socket_path(session_id)`.
 * Do not add a second argument here; it would be unused at runtime and
 * obscure the invariant that the webview cannot steer this connection.
 */
export async function sessionHello(sessionId: SessionId): Promise<HelloAck> {
  return invoke<HelloAck>('session_hello', { sessionId });
}

export async function sessionSubscribe(
  sessionId: SessionId,
  since = 0,
): Promise<void> {
  await invoke('session_subscribe', { sessionId, since });
}

export async function sessionSendMessage(
  sessionId: SessionId,
  text: string,
): Promise<void> {
  await invoke('session_send_message', { sessionId, text });
}

export async function sessionApproveTool(
  sessionId: SessionId,
  toolCallId: ToolCallId,
  scope: ApprovalScope,
): Promise<void> {
  await invoke('session_approve_tool', { sessionId, toolCallId, scope });
}

export async function sessionRejectTool(
  sessionId: SessionId,
  toolCallId: ToolCallId,
  reason?: string,
): Promise<void> {
  await invoke('session_reject_tool', { sessionId, toolCallId, reason });
}

// ---------------------------------------------------------------------------
// F-036: persistent approval commands
// ---------------------------------------------------------------------------

/**
 * Load all persistent approvals (workspace + user) for seeding the per-session
 * whitelist at session start. Workspace entries win on `scope_key` collision
 * with user entries (mirrors `forge-mcp::config::load_merged`).
 *
 * `PersistentApprovalEntry` is generated by ts-rs from the Rust shape in
 * `forge-shell::ipc` — keep the two in sync by regenerating after any field
 * change, not by patching this file.
 */
export async function getPersistentApprovals(
  workspaceRoot: string,
): Promise<PersistentApprovalEntry[]> {
  return invoke<PersistentApprovalEntry[]>('get_persistent_approvals', {
    workspaceRoot,
  });
}

/**
 * Upsert `entry` into the config for `level`. Session-level saves are a no-op
 * on the backend but remain defensively accepted so a mis-routed caller fails
 * soft. Frontend call-sites should skip the invoke for `'session'` to avoid
 * an unnecessary round trip.
 */
export async function saveApproval(
  entry: ApprovalEntry,
  level: ApprovalLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('save_approval', { entry, level, workspaceRoot });
}

/**
 * Drop the matching entry from the config for `level`. Session-level removal
 * is a no-op on the backend for the same reason as `saveApproval`.
 */
export async function removeApproval(
  scopeKey: string,
  level: ApprovalLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('remove_approval', { scopeKey, level, workspaceRoot });
}

/**
 * Subscribe to session events from the shell. Returns an unlisten handle.
 * The callback receives the payload unwrapped from Tauri's event envelope.
 */
export async function onSessionEvent(
  handler: (payload: SessionEventPayload) => void,
): Promise<UnlistenFn> {
  return listen<SessionEventPayload>(SESSION_EVENT, (event) => {
    handler(event.payload);
  });
}

// ---------------------------------------------------------------------------
// F-137 / F-138: background-agent lifecycle commands.
//
// The Status-bar `BgAgentsBadge` (F-138) calls `listBackgroundAgents` on mount
// (post-reconnect recovery) and subscribes to `session:event` for live
// lifecycle updates. Popover Promote/Stop buttons route through
// `promoteBackgroundAgent` / `stopBackgroundAgent`.
// ---------------------------------------------------------------------------

export async function listBackgroundAgents(
  sessionId: SessionId,
): Promise<BgAgentSummary[]> {
  return invoke<BgAgentSummary[]>('list_background_agents', { sessionId });
}

export async function promoteBackgroundAgent(
  sessionId: SessionId,
  instanceId: string,
): Promise<void> {
  await invoke('promote_background_agent', { sessionId, instanceId });
}

export async function stopBackgroundAgent(
  sessionId: SessionId,
  instanceId: string,
): Promise<void> {
  await invoke('stop_background_agent', { sessionId, instanceId });
}

// ---------------------------------------------------------------------------
// F-151: persistent settings commands
// ---------------------------------------------------------------------------

/** Tier a `set_setting` write targets. */
export type SettingsLevel = 'user' | 'workspace';

/**
 * Load the merged user + workspace settings for the given workspace root.
 * The shell deep-merges at TOML-tree granularity — a workspace file that
 * declares only `[notifications]` does NOT overwrite the user's `[windows]`
 * preferences. Missing files on either tier fall through to defaults.
 */
export async function getSettings(workspaceRoot: string): Promise<AppSettings> {
  return invoke<AppSettings>('get_settings', { workspaceRoot });
}

/**
 * Persist a single setting at the requested tier. `key` is a dotted path
 * (e.g. `"notifications.bg_agents"`); `value` is the JSON-serializable scalar
 * (or table) to land at that location. The shell validates the value by
 * round-tripping the updated TOML tree through `AppSettings`, so bad types
 * are rejected before anything lands on disk.
 *
 * Sibling fields already present in the file survive — the backend applies
 * the update in-place on the raw TOML tree rather than serializing a full
 * struct, which is the guarantee that lets the merge semantic (workspace
 * overrides user on declared fields only) hold across repeated writes.
 */
export async function setSetting(
  key: string,
  value: unknown,
  level: SettingsLevel,
  workspaceRoot: string,
): Promise<void> {
  await invoke('set_setting', { key, value, level, workspaceRoot });
}
